### PR TITLE
add human_trajectory package to indigo-devel branch

### PR DESCRIPTION
**Pull request by ferdianjovan**

### CODE REVIEW

**Comment by cdondrup** [comment]
There is no install target defined and also no `setup.py`. I understand that `trajectory.py` should be executable so it should be in a `scripts` directory and installed via the CMakeLists.txt. Please see discussion here: https://github.com/strands-project/strands_ui/pull/66 and add the install target like here: https://github.com/strands-project/strands_ui/blob/hydro-devel/music_player/CMakeLists.txt#L27 otherwise it wouldn't do anything after the installation.

**Comment by cdondrup** [comment]
One last request, can you please also add your package to the metapackage and adjust the version number to be equal to the numbers in the other packages?

**Comment by ferdianjovan** [comment]
Ok, I will work on that as well.

**Comment by cdondrup** [comment]
Thank you! If you need help, please let me know. But I'm very confident you wont :)

**Comment by marc-hanheide** [comment]
@cdondrup you happy now?

**Comment by cdondrup** [comment]
Almost. I'll fix the rest before releasing it.
Thank you @ferdianjovan

**Comment by ferdianjovan** [comment]
Ah, almost got an A mark from @cdondrup  :)

**Comment by marc-hanheide** [comment]
Almost :smile:

**Comment by cdondrup** [comment]
Very close ;)

**Pull request merged**
