### PR TITLE
Slight changes to the fixed ground plane to enable HOG feature extraction on the robot

### PR DESCRIPTION
**Pull request by cdondrup**
These changes are necessary to make the HOG extraction work with the fixed ground plane.
Tested on Linda.

### CODE REVIEW

**Comment by hawesie** [comment]
Who should be checking this before I merge it?

**Comment by cdondrup** [comment]
Lars is currently working on that. Maybe he can check.

**Comment by hawesie** [comment]
@kunzel?

**Comment by kunzel** [comment]
I will look into it tomorrow.

**Comment by kunzel** [comment]
Technically, everything is working. However, the performance of the people tracker based on HOG features is not very good. The detections based on HOG features look promising, but the compination with the tracker isn't working very well. I will try to sort this out with @cdondrup's help tomorrow.

**Comment by hawesie** [comment]
Ok, give me a thumbs-up when you're happy enough to merge it.

**Comment by cdondrup** [comment]
@kunzel Since this works and does not change the behaviour of the ppl perception we use currently, I think we should merge it even though the HOG features do not really improve detections. You can still run it without it and get the same tracker as before. What do you think?

**Comment by kunzel** [comment]
@cdondrup, agreed. @hawesie, please merge it.

**Pull request merged**
