### PR TITLE
Renaming most of the packages to comply with ROS naming conventions

### PR DESCRIPTION
**Pull request by cdondrup**
This requires all the PRs below to be merged.

### CODE REVIEW

**Comment by cdondrup** [comment]
I didn't rename the `strands_pedestrian_tracking` because I couldn't come up with a nice name. Maybe @lucasb-eyer has an idea or it will remain like that.

**Comment by cdondrup** [comment]
I will merge this in order to proceed with the release.

**Comment by lucasb-eyer** [comment]
I don't know what a "nice name" is in the beautiful world of ROS, but what's wrong with `pedestrian_tracker`? Alternatively, `mdl_pedestrian_tracker`, because it's using "Minimum Description Length". It should keep `pedestrian` in the name since it likely won't work for things like cars because of a bunch of assumptions.

**Comment by cdondrup** [comment]
I just wasn't sure about the "pedestrian" in there because pedestrians are just a subset of all the people but it works on non-pedestrians as well.

**Comment by lucasb-eyer** [comment]
Oh good point! It's supposed to become a people tracker, but for now it's a pedestrian tracker. You could preemptively rename it to `people_tracker`.

**Comment by cdondrup** [comment]
There already is a `people_tracker` in ROS. Could rename it to `mdl_people_tracker`?!

**Comment by lucasb-eyer** [comment]
yep, that works.

**Pull request merged**
