### PR TITLE
updated trajectory message to include the displacement

### PR DESCRIPTION
**Pull request by PDuckworth**
...and displacement_to_pose ratio used for filtering.

@ferdianjovan Please can you test both online and offline cases?

### CODE REVIEW

**Comment by ferdianjovan** [comment]
Ok, I will test them during the weekend.

**Comment by PDuckworth** [comment]
@hawesie This has been tested both offline and online by Ferdian and myself. Can you please merge?

**Comment by cdondrup** [comment]
I'm not @hawesie and this PR seem to do more than just updating the message but if you tested it I'm happy.

**Comment by ferdianjovan** [comment]
Ah, thanks @cdondrup :)

**Comment by PDuckworth** [comment]
Thank you @cdondrup

**Pull request merged**
