### PR TITLE
Added 2 further configs to the bayes_people_tracker

### PR DESCRIPTION
**Pull request by Pandoro**
One with only the mobility aid detector and one with all 3 detectors.

### CODE REVIEW

**Comment by cdondrup** [comment]
In general I think it might be better to just add the wheelchair detector to the `detectors.yaml`. In fact it doesn't matter if one of the detectors defined in there is not running it will simply ignore it then. So just adding all of them to the same config file and then starting the tracker separately from the detectors, you can simply turn the detectors on or off to your liking while the tracker is running.

For now, what ever works for the review is fine of course but in general I think we can add the draw to the list of detectors so if it is running the tracker will use it.

**Comment by Pandoro** [comment]
Aaah okay! I wasn't aware of that. In fact it was kind of annoying like this, since when you kill the tracker to restart it with another config, the detectors in rosparam are overwritten, but not deleted. Let's discuss this on Monday in detail, we wanted to show all three scenarios for which I made the configs, but I like your idea a little better. That would however mean we have to start all detectors separately.

**Comment by marc-hanheide** [comment]
superseded by #201

**Comment by cdondrup** [comment]
@Pandoro exactly. Just spawning a few tux windows should do the trick. Shouldn't be too complicated. Just have to make sure that all the parameters and topics are correct compared to the master launch file.

**Pull request closed without merging**
