### PR TITLE
Reading parameters from datacentre

### PR DESCRIPTION
**Pull request by cdondrup**
Needs: https://github.com/strands-project/ros_datacentre/pull/67 to be merged.

The ppl perception pipeline has a lot of parameters and models scattered over several packages and config files. This led to problems when starting this remotely on another machine via launch files. The path for the config files had to be hard coded into the launchfile (for a, at least for me, unknown reason) or they could not be found. Trying to launch this remotely on Rosie did not work at all due to the different filesystem architectures on the embedded and side PC and therefore not found config files. I think that reading all these parameters from the datacentre would be much easier for the user. Also, all the models (upper body and groundHOG) are now provided as parameters in the datacentre.

The whole thing can still be started without the datacentre running. For this reason I created a new parameter `with_datacentre` which defaults to `true` if you run one of the `*_robot*.launch` files and `false` if you run one of the `*_standalone*.launch` files. If set to `true` the nodes assume the datacentre to be there containing the necessary parameters (see: https://github.com/strands-project/ros_datacentre/pull/67). If the parameter is `false` then the parameters will be read from the yaml files in the respective `config` directories of the packages.

To run the ground_hog detection using parameters instead of a config file, I had to patch the libcudaHOG a bit more which requires to recompile it: https://github.com/strands-project/strands_perception_people/tree/hydro-devel/3rd_party#installation but I think only @kunzel and @marc-hanheide did install this so far so that should not be a problem.
One issue with this is, that the licudaHOG reads the model from a binary (God knows why...) and does a lot of fseek magic according to a magic version number in the file which I was not willing to rewrite. Therefore the model is read from the parameter server by the `strands_ground_hog` node and then written to `/tmp` from which libcudaHOG reads it. I am aware that this is quite dirty but it saved me a lot of work. Since I don't get paid to improve the ppl perception I chose this quick and dirty solution that still works fine.

It would be nice if @kunzel could test this (sorry for being my testing guy) and also @RaresAmbrus or @nilsbore to see if you are now able to start the ppl perception remotely using the machine tags.

### CODE REVIEW

**Comment by cdondrup** [comment]
Don't merge until we have a new location for the default parameters.

**Comment by cdondrup** [comment]
Needs https://github.com/strands-project/strands_deployment/pull/35 merged.

**Comment by cdondrup** [comment]
Did anyone have time to take a look at that yet?

**Comment by cdondrup** [comment]
Could any try this please? I would like to merge it because it would get rid of the license and copyright included in the ConfigFile.h which would be nice for the release version.

**Comment by hawesie** [comment]
I am just installing all this on a standalone machine for a non-robot demo. Once that's working I'll test this.

**Comment by cdondrup** [comment]
Thank you! 
I'm just about to rename the parameter. Will push that in 5 minutes.

**Comment by cdondrup** [comment]
Ok, the parameter `with_datacentre` has been renamed to `load_params` and works the other way around, which makes more sense imho.

The `*_robot*.launch` files assume this parameter to be false and therefore assume the parameters to be available from the parameter server. The `*_standalone*.launch` files assume that the parameters server does not hold the parameters and loads them from the config files. This basically reflects that on the robot we will have a mongodb_store providing the default params whereas on a standalone setup we cannot assume the mongodb_store to be running.

Calling `roslaunch strands_perception_people_launch pedestrian_tracker_*.launch load_params:=<true|false>` forces the launch file to either load the parameters from the files (`true`) or to ignore the files (`false`), trying to get the parameters from the server.

**Comment by cdondrup** [comment]
Did you manage to test this yesterday, @hawesie?

**Comment by hawesie** [comment]
Sorry, no, and probably not until Friday or Saturday due to limited hacking time this week.=

**Comment by hawesie** [comment]
Sorry, I've had a frantic week and still haven't tried this.

**Comment by hawesie** [comment]
I tested this with...

```
roslaunch mongodb_store mongodb_store.launch defaults_path:=`rospack find strands_parameters`/defaults
roslaunch strands_perception_people_launch pedestrian_tracker_standalone.launch load_params:=false
```

... and everything ran fine. So, this is fine to merge, although I suggest one change. `load_params` is an ambiguous name as in either case the params are loaded, but the value changes where they are loaded from. I'd suggest something more like `mongodb_params` or `params_from_file` to make it explicit what the flag is doing. Apart from this, I think you can merge away.

**Comment by cdondrup** [comment]
OK, I'll change that and merge it afterwards.
Thanks for testing!

**Pull request merged**
