### PR TITLE
People tracking: a more dynamic and flexible approach

### PR DESCRIPTION
**Pull request by cdondrup**
This is quite a substantial change to the current people perception. 
- The rather useless node `pedestrian_localisation` has now become the `people_tracker`. Please see strands_people_tracker/README.md for a detailed description of the functionality.
  - This node uses a bayestracking library to combine multiple detectors like the upper_body_detector and a leg detector. The library is included as a submodule and wstool should take care of initialising this. If you try to build it without using wstool to clone it remember to do a `git submodule init` and `git submodule update` before trying to build it.
  - The results of this tracker seem to be more accurate than the Aachen pedestrian tracker working on the same detections coming from the upper body detector. Therefore the pedestrain_tracker is not the tracker of choice any more. 
  - The tracker now also publishes at 30hz regardless of the actual detector speed.
  - The pedestrain_localisation message doesn't exist any more and has been refactored into the PeopleTracker message.
- The logging has been adapted to use the right message types and the uuid generated by the people_tracker instead of the pedestrian_tracker.
  - Down side: until someone implements proper ids for the upper body detector which can be used in both trackers, the tracking results from the people and pedestrian tracker will have different ids. This is not really relevant because the pedestrian tracker should be deprecated with this PR
  - The tf look up in the logging now also uses the correct time and not just `ros::Time::now()`
- The upper body detector now publishes a marker array to visualise the detections
- The pedestrian tracker publishes a marker array to visualise the results and a PoseArray in the given target frame for logging purposes.

### CODE REVIEW

**Comment by kunzel** [comment]
Sounds cool, we will give it a try today!

**Comment by cdondrup** [comment]
Thanks! Let me know if you find anything.

**Comment by kunzel** [comment]
@cdondrup, any idea how to solve this CMake error?

```
CMake Error at strands_perception_people/strands_people_tracker/CMakeLists.txt:1
8 (find_package):
  Could not find module FindBayestracking.cmake or a configuration file for
  package Bayestracking.

  Adjust CMAKE_MODULE_PATH to find FindBayestracking.cmake or set
  Bayestracking_DIR to the directory containing a CMake configuration file
  for Bayestracking.  The file will have one of the following names:

    BayestrackingConfig.cmake
    bayestracking-config.cmake
```

**Comment by cdondrup** [comment]
Oops, should work now.

**Comment by kunzel** [comment]
Great, now it compiled :) I will test it now... But before merging the pull request, you should also prepare a second PR for strands_msgs.

**Comment by cdondrup** [comment]
I'm getting more and more forgetful...
This PR needs: https://github.com/strands-project/strands_msgs/pull/25 merged.

**Pull request merged**
