### PR TITLE
Removing 3rd_party package which is now in attic branch

### PR DESCRIPTION
**Pull request by cdondrup**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
seems the indigo-devel branch is not set up to check pull requests, yet? Which is strange as there is https://github.com/strands-project/rosdistro/blob/strands-devel/indigo/distribution.yaml#L8024 and also the job does exist: https://lcas.lincoln.ac.uk/jenkins/view/Pull%20Requests/job/pr-indigo-strands_perception_people/

**Comment by marc-hanheide** [comment]
retest this please

**Comment by cdondrup** [comment]
The `indigo-release` is set-up as there was no `indigo-devel` before the winter school. If you could change that, that would be great since the release branches will be gone soon any way.

**Comment by marc-hanheide** [comment]
oh, you are so right... It's set wrongly

**Comment by marc-hanheide** [comment]
corrected now

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
now jenkins works

**Pull request merged**
